package controller;

import application.UnternehmerObserver;
import application.Verwaltung;
import javafx.fxml.FXML;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import model.Nutzer;
import model.Unternehmensprofil;

public class ViewURahmen implements UnternehmerObserver {

	@FXML
	private ImageView homebutton;
	@FXML
	private ImageView profilbutton;
	@FXML
	private ImageView searchbutton;
	@FXML
	private ImageView settingsbutton;
	@FXML
	private ImageView signoutbutton;
	@FXML
	private ImageView userpicture;
	@FXML
	private ImageView addofferbutton;

	public void initialize() {
		Verwaltung.getInstance().registerAsUnternehmer(this);
	}

	// Event Listener on ImageView[#homebutton].onMouseClicked
	@FXML
	public void openHome(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#profilbutton].onMouseClicked
	@FXML
	public void openProfil(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#searchbutton].onMouseClicked
	@FXML
	public void openSearch(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#settingsbutton].onMouseClicked
	@FXML
	public void openSettings(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#signoutbutton].onMouseClicked
	@FXML
	public void openSignOut(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#addofferbutton].onMouseClicked
	@FXML
	public void createnewoffer(MouseEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void updateUnternehmer(Unternehmensprofil aUnternehmer) {
		// TODO Auto-generated method stub

	}

	@Override
	public void updateNutzer(Nutzer aNutzer) {
		// TODO Auto-generated method stub

	}

}
