package view3;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Pane;

public class ViewFRahmen {
	@FXML
	private ImageView homebutton;
	@FXML
	private ImageView profilbutton;
	@FXML
	private ImageView searchbutton;
	@FXML
	private ImageView settingsbutton;
	@FXML
	private ImageView signoutbutton;
	@FXML
	private ImageView userpicture;
	@FXML
	private ImageView addofferbutton;
	@FXML
	private AnchorPane pane;
	@FXML
	private Label titel;

	private void openStage() {

	}

	private void openSubScene(String datei, String name) {
		try {
			Pane myPane = FXMLLoader.load(getClass().getResource(datei));
			pane.getChildren().clear();
			pane.getChildren().add(myPane);
			titel.setText(name);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	public void initialize() {
		openSubScene("FDashboard.fxml", "Dashboard");
	}

	// Event Listener on ImageView[#homebutton].onMouseClicked
	@FXML
	public void openHome(MouseEvent event) {
		openSubScene("FDashboard.fxml", "Dashboard");
	}

	// Event Listener on ImageView[#profilbutton].onMouseClicked
	@FXML
	public void openProfil(MouseEvent event) {
		openSubScene("FProfil.fxml", "Profil bearbeiten");
	}

	// Event Listener on ImageView[#searchbutton].onMouseClicked
	@FXML
	public void openSearch(MouseEvent event) {
		openSubScene("FSuche.fxml", "Suche");
	}

	// Event Listener on ImageView[#settingsbutton].onMouseClicked
	@FXML
	public void openSettings(MouseEvent event) {
		openSubScene("Settings.fxml", "Einstellungen");
	}

	// Event Listener on ImageView[#signoutbutton].onMouseClicked
	@FXML
	public void openSignOut(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#addofferbutton].onMouseClicked
	@FXML
	public void createNewOffer(MouseEvent event) {
		openStage();
	}
}
